### PR TITLE
Enable LGTM.com analysis for C/C++ code

### PR DESCRIPTION
**Pull request by sjvs**
Hi team!

I noticed that you've recently enabled LGTM's automatic code review for pull requests, but that your C/C++ code wasn't being analysed. This `lgtm.yml` file should install the right dependencies that we couldn't automatically detect (working on a fix to the auto-detection); C/C++ results are on their way! If you ever need to tweak your build process for LGTM: https://lgtm.com/help/lgtm/cpp-extraction

This `lgtm.yml` also lists some modules as 'library' code — do add more if you think I've missed some. You obviously know the code base much better than me. Last but not least: an LGTM badge :slightly_smiling_face: 

Feel free to tweak the PR!

### CODE REVIEW

**Comment by Nelson-numerical-software** [comment]
Thanks you for help !
I discovered LGTM yesterday and I planned to plug it next days.
I also created a ticket about warnings detected by LGTM. I will try to fix it for v0.2.10 
Thanks

**Comment by Nelson-numerical-software** [comment]
@sj Hi, can you help me about current build on LGTM.
What is missing ?
Thanks

**Comment by sj** [comment]
I'm away from my laptop for a couple of days, but @jhutchings1 might be 
able to help!

**Comment by jhutchings1** [comment]
👋🏻  @Nelson-numerical-software Feel free to let me know what issues you're hitting and we can have a look. 

You might also be interested in trying the new native capability called code scanning: https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning

**Comment by Nelson-numerical-software** [comment]
@jhutchings1 
https://lgtm.com/projects/g/Nelson-numerical-software/nelson/logs/languages/lang:cpp
```
Semmle autobuild: no supported build system detected.
```
Can  you confirm that it due to 'ninja' build ?

(Thanks)

**Comment by jbj** [comment]
Ninja is supported, but the log shows that we're not using it. Our autobuilder invokes CMake as:

```
cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_DOCS=OFF -DCATKIN_ENABLE_TESTING=OFF -DBUILD_DOCUMENTATION=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-fpermissive ..
```

If you want to build with Ninja, I think you need to add `-G Ninja` to that command line. Our autobuilder doesn't do that by default since most projects are better tested with the default generator than with generators that must be opted into explicitly.

The fatal error appears near the end of the log you linked, when the build is 97% done:

```
[2020-09-28 17:15:31] [build] cd /opt/src/_lgtm_build_dir/modules/main && ../../bin/linux64/nelson-cli --nousermodules --noipc --quiet --file /opt/src/_lgtm_build_dir/bin/linux64/../../tools/gettext/generatemo.nls
[2020-09-28 17:15:31] [build] /bin/sh: 1: ../../bin/linux64/nelson-cli: not found
```

Further up above, the build system creates `../../bin/linux64/nelson-cli-exec`. Should that have been named `nelson-cli`?

Is the project supposed to be buildable in the default (Unix Makefiles) mode? On Ubuntu 19.10? If not, you can change the `configure` `command` in the project's `lgtm.yml`: https://lgtm.com/help/lgtm/lgtm.yml-configuration-file.

**Comment by Nelson-numerical-software** [comment]
@jbl
Nelson build on ubuntu 19, 20, Ubuntu, arch,
https://github.com/Nelson-numerical-software/nelson/actions/runs/275382615

```
[2020-09-28 17:15:31] [build] /bin/sh: 1: ../../bin/linux64/nelson-cli: not found
```
nelson-cli is an existing script 

https://github.com/Nelson-numerical-software/nelson/tree/master/bin/linux64

Strange that ```nelson-cli``` seems to be missing here. 

Thanks for you help

**Comment by jbj** [comment]
The failing command is

```
cd /opt/src/_lgtm_build_dir/modules/main && ../../bin/linux64/nelson-cli ...
```

When the current directory is `/opt/src/_lgtm_build_dir/modules/main`, the `../..` refers to `/opt/src/_lgtm_build_dir`, but the script we're trying to invoke actually resides one level higher up.

Perhaps your build system assumes that the user will perform an in-source build, that is, `cmake . && make`? LGTM does an out-of-source build unless told otherwise in `lgtm.yml` since that has shown the highest success rate in practice and is also the recommended best practice. See https://cliutils.gitlab.io/modern-cmake/chapters/intro/running.html. Our `_lgtm_build_dir` directory is what's called `build` in that text.

**Comment by Nelson-numerical-software** [comment]
Thanks for your advice
It seems currently fixed in a branch
image
It will see results when it will be in master
https://lgtm.com/projects/g/Nelson-numerical-software/nelson/logs/rev/pr-0aeb216954b1cdb185a8bb751e949ab006c21b29/lang:cpp/stage:Build%20merge_0df9c465038f852bee3f4a60b90495a760a2371a

**Pull request merged**
