### PR TITLE
Temporarily revert to old CodeQL version

### PR DESCRIPTION
**Pull request by aibaars**
### What was a problem?

https://github.com/github/codeql/issues/10194

### How this Pull Request fixes the problem?

Switch to the 2.10.4 (pre-release) version of CodeQL , which includes https://github.com/github/codeql/pull/10128

@Nelson-numerical-software

### CODE REVIEW

**Review by Nelson-numerical-software — APPROVED** [review]
Good News , it works :)

**Comment by aibaars** [comment]
Let's also try with the new version . Hopefully the future release already fixes the performance issue.

**Comment by aibaars** [comment]
@Nelson-numerical-software Could you approve running the workflow for https://github.com/Nelson-numerical-software/nelson/pull/716/commits/b8d219e4481634a430fb14df760cbe1648a2eda8 ?

**Comment by Nelson-numerical-software** [comment]
> @Nelson-numerical-software Could you approve running the workflow for [b8d219e](https://github.com/Nelson-numerical-software/nelson/commit/b8d219e4481634a430fb14df760cbe1648a2eda8) ?

run in progress

**Comment by aibaars** [comment]
@Nelson-numerical-software This is read for merge now. This workaround can be removed once CodeQL 2.10.4 is the default on the GitHub Actions VMs. I expect this to happen in about 10 days from now.

**Review by Nelson-numerical-software — APPROVED** [review]

**Pull request merged**
